services:
  - type: web
    name: taskmart-json-server
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: JSON_SERVER_PORT
        value: 3001
      - key: JWT_SECRET
        value: taskmart-test-secret-2024
